document.querySelectorAll('.menu').forEach(button=>button.addEventListener('click',()=>{document.querySelector('nav').classList.toggle('open')}));
const visionContent=document.querySelector('.vision-content'); if(visionContent){visionContent.style.display='none';}
document.querySelector('.about-image img')?.addEventListener('error',event=>{event.currentTarget.src='arte-otros-ojos-banner.png'});
const show=(id)=>document.getElementById(id)?.classList.add('visible');
const hide=(id)=>document.getElementById(id)?.classList.remove('visible');
document.querySelectorAll('.service-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.service-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');hide('classes-panel');hide('party-panel');show(b.dataset.service==='classes'?'classes-panel':'party-panel')}));
let classFrequency=0, guests='small', decor=0, duration=0, honoree=0;
document.querySelectorAll('.class-age').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.class-age').forEach(x=>x.classList.remove('active'));b.classList.add('active');show('class-frequency')}));
document.querySelectorAll('.frequency-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.frequency-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');classFrequency=Number(b.dataset.frequency);const session=classFrequency===2?12:15;document.getElementById('session-price').textContent=session+' €';document.getElementById('weekly-price').textContent=(session*classFrequency)+' €';document.getElementById('monthly-price').textContent=(session*classFrequency*4)+' €';document.getElementById('quarterly-price').textContent=(session*classFrequency*12*0.95).toFixed(0)+' €';document.getElementById('semester-price').textContent=(session*classFrequency*24*0.9).toFixed(0)+' €';show('class-prices')}));
const updateParty=()=>{if(!guests||!decor||!duration||!honoree)return;const base={small:145,medium:220,large:320}[guests];const total=base+decor*35+(duration===120?30:duration===180?65:0);document.getElementById('party-total').textContent=total+' €';document.getElementById('party-includes').textContent=decor?'Material + decoración':'Material artístico';show('party-price')};
document.querySelectorAll('.guest-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.guest-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');guests=b.dataset.guests;show('party-options');updateParty()}));
document.querySelectorAll('.decor-choice').forEach((b,i)=>b.addEventListener('click',()=>{document.querySelectorAll('.decor-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');decor=i;updateParty()}));
document.querySelectorAll('.duration-choice').forEach((b,i)=>b.addEventListener('click',()=>{document.querySelectorAll('.duration-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');duration=[90,120,180][i];updateParty()}));
document.querySelectorAll('.honoree-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.honoree-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');honoree=1;updateParty()}));

